//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientOfSchoolService.MySchoolWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySchoolWebService.SchoolWebServiceSoap")]
    public interface SchoolWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name serializedNewStudent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        ClientOfSchoolService.MySchoolWebService.AddResponse Add(ClientOfSchoolService.MySchoolWebService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name ReadAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadAll", ReplyAction="*")]
        ClientOfSchoolService.MySchoolWebService.ReadAllResponse ReadAll(ClientOfSchoolService.MySchoolWebService.ReadAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public ClientOfSchoolService.MySchoolWebService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(ClientOfSchoolService.MySchoolWebService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serializedNewStudent;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string serializedNewStudent) {
            this.serializedNewStudent = serializedNewStudent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientOfSchoolService.MySchoolWebService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(ClientOfSchoolService.MySchoolWebService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAll", Namespace="http://tempuri.org/", Order=0)]
        public ClientOfSchoolService.MySchoolWebService.ReadAllRequestBody Body;
        
        public ReadAllRequest() {
        }
        
        public ReadAllRequest(ClientOfSchoolService.MySchoolWebService.ReadAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadAllRequestBody {
        
        public ReadAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientOfSchoolService.MySchoolWebService.ReadAllResponseBody Body;
        
        public ReadAllResponse() {
        }
        
        public ReadAllResponse(ClientOfSchoolService.MySchoolWebService.ReadAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadAllResult;
        
        public ReadAllResponseBody() {
        }
        
        public ReadAllResponseBody(string ReadAllResult) {
            this.ReadAllResult = ReadAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SchoolWebServiceSoapChannel : ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolWebServiceSoapClient : System.ServiceModel.ClientBase<ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap>, ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap {
        
        public SchoolWebServiceSoapClient() {
        }
        
        public SchoolWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientOfSchoolService.MySchoolWebService.AddResponse ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap.Add(ClientOfSchoolService.MySchoolWebService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(string serializedNewStudent) {
            ClientOfSchoolService.MySchoolWebService.AddRequest inValue = new ClientOfSchoolService.MySchoolWebService.AddRequest();
            inValue.Body = new ClientOfSchoolService.MySchoolWebService.AddRequestBody();
            inValue.Body.serializedNewStudent = serializedNewStudent;
            ClientOfSchoolService.MySchoolWebService.AddResponse retVal = ((ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientOfSchoolService.MySchoolWebService.ReadAllResponse ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap.ReadAll(ClientOfSchoolService.MySchoolWebService.ReadAllRequest request) {
            return base.Channel.ReadAll(request);
        }
        
        public string ReadAll() {
            ClientOfSchoolService.MySchoolWebService.ReadAllRequest inValue = new ClientOfSchoolService.MySchoolWebService.ReadAllRequest();
            inValue.Body = new ClientOfSchoolService.MySchoolWebService.ReadAllRequestBody();
            ClientOfSchoolService.MySchoolWebService.ReadAllResponse retVal = ((ClientOfSchoolService.MySchoolWebService.SchoolWebServiceSoap)(this)).ReadAll(inValue);
            return retVal.Body.ReadAllResult;
        }
    }
}
